import "./globals.css";
import { Bars3Icon } from "@heroicons/react/24/solid";
import Footer from "./Footer";
import Navigation from "./Navigation";

export const metadata = {
  title: "BachMacintosh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body>
        <div className="drawer drawer-mobile">
          <input
            id="my-drawer-2"
            type="checkbox"
            className="drawer-toggle"
          />
          <div className="drawer-content flex flex-col items-center">
            <label
              htmlFor="my-drawer-2"
              className="btn btn-primary drawer-button w-full sticky top-0 lg:hidden text-2xl uppercase font-extrabold"
            >
              <Bars3Icon className="w-12 h-6 mt-1" />
              BachMacintosh
            </label>
            <div className="max-w-7xl w-full mx-3 mt-5 text-base-content">
              {children}
              <Footer />
            </div>
          </div>
          <Navigation />
        </div>
      </body>
    </html>
  );
}
