name: Build (Push)
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy on Push/Dispatch
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SANITY_API_VERSION: ${{vars.NEXT_PUBLIC_SANITY_API_VERSION}}
      NEXT_PUBLIC_SANITY_DATASET: ${{vars.NEXT_PUBLIC_SANITY_DATASET}}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{vars.NEXT_PUBLIC_SANITY_PROJECT_ID}}
      SANITY_TOKEN: ${{secrets.SANITY_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install Dependencies
        run: npm ci
      - name: Build Next.js App
        run: "npm run build"
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "unnecessary"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -az --delete . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIRECTORY }}
      - name: Reload Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: pm2 reload www
